name: spectral_connectivity
channels:
- conda-forge
- defaults
dependencies:
# Core dependencies (match pyproject.toml)
- python>=3.10
- "numpy >= 1.24, <3.0"
- "scipy >= 1.10"
- "xarray >= 2023.1"
- "matplotlib >= 3.7"
- nitime

# Development and testing
- "pytest >= 8.0"
- "pytest-cov >= 4.1"
- "mypy >= 1.8"

# Code formatting and linting
- "black >= 24.0"
- "ruff >= 0.8.0"

# Documentation
- "numpydoc >= 1.6"
- sphinx
- sphinx-copybutton
- sphinx-autoapi

# Jupyter environment
- jupyter
- jupyterlab

# CI/Build tools
- coveralls
- hatch
- build
- twine
