name: spectral_connectivity
channels:
- conda-forge
- defaults
dependencies:
- numpy >= 1.11
- matplotlib
- scipy
- xarray
- nitime
- "pytest >= 2.7.1"
- pytest-cov
- coveralls
- setuptools
- black
- flake8
- jupyter
- numpydoc
- sphinx
- sphinx-copybutton
- sphinx-autoapi
- jupyter
- jupyterlab
- nb_conda
