name: spectral_connectivity
channels:
- conda-forge
- defaults
dependencies:
- python>=3.6
- numpy
- matplotlib
- scipy
- xarray
- nitime
- pytest
- pytest-cov
- coveralls
- setuptools
- jupyter
- numpydoc
- sphinx
