name: spectral_connectivity
channels:
- conda-forge
- defaults
dependencies:
# Core dependencies (match pyproject.toml)
- "numpy >= 1.21"
- "scipy >= 1.7"
- "xarray >= 0.20"
- "matplotlib >= 3.4"
- nitime

# Development and testing
- "pytest >= 7"
- pytest-cov
- "mypy >= 1.0"
- pydocstyle

# Code formatting and linting
- black
- flake8

# Documentation
- numpydoc
- sphinx
- sphinx-copybutton
- sphinx-autoapi

# Jupyter environment
- jupyter
- jupyterlab

# CI/Build tools
- coveralls
- hatch
- build
